name: Build and Push Services

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io/briitz 
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: docker.io/briitz

      - name: Build & push services
        run: |
          for service in services/*; do
            if [ -f "$service/Dockerfile" ]; then
              SERVICE_NAME=$(basename $service)
              echo "Building and pushing $SERVICE_NAME..."
              docker build -t $REGISTRY/$SERVICE_NAME:$IMAGE_TAG $service
              docker push $REGISTRY/$SERVICE_NAME:$IMAGE_TAG
            fi
          done
